cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_splines.F90 .
cp /home/hexu/projects/abinit/shared/common/src/14_hidewrite/m_fstrings.F90 .
cp /home/hexu/projects/abinit/shared/common/src/18_timing/m_time.F90 .
cp /home/hexu/projects/abinit/src/41_geometry/m_gtermcutoff.F90 .
cp /home/hexu/projects/abinit/shared/common/src/14_hidewrite/m_io_tools.F90 .
cp /home/hexu/projects/abinit/shared/common/src/14_hidewrite/m_specialmsg.F90 .
cp /home/hexu/projects/abinit/shared/common/src/32_util/m_symtk.F90 .
cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_numeric_tools.F90 .
cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_hide_lapack.F90 .
cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_linalg_interfaces.F90 . 
cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_slk.F90 .
cp /home/hexu/projects/abinit/build/shared/common/src/14_hidewrite/m_build_info.F90 . 
cp /home/hexu/projects/abinit/shared/common/src/14_hidewrite/m_cppopts_dumper.F90 .
cp /home/hexu/projects/abinit/build/shared/common/src/14_hidewrite/m_optim_dumper.F90 .
cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_bessel.F90 .
cp /home/hexu/projects/abinit/shared/libpaw/src/m_paw_numeric.F90 .
cp /home/hexu/projects/abinit/shared/libpaw/src/m_libpaw_defs.F90 .
cp /home/hexu/projects/abinit/shared/libpaw/src/m_libpaw_tools.F90 .
cp /home/hexu/projects/abinit/shared/libpaw/src/m_libpaw_mpi.F90 .
cp /home/hexu/projects/abinit/src/41_geometry/m_geometry.F90 .
cp /home/hexu/projects/abinit/shared/common/src/18_timing/m_xpapi.F90 .
cp /home/hexu/projects/abinit/shared/common/src/32_util/m_atomdata.F90 .
cp /home/hexu/projects/abinit/shared/common/src/28_numeric_noabirule/m_sort.F90 .
cp /home/hexu/projects/abinit/shared/common/src/32_util/m_pptools.F90 .
cp /home/hexu/projects/abinit/shared/common/src/17_libtetra_ext/m_krank.F90 .
cp /home/hexu/projects/abinit/shared/common/src/32_util/m_special_funcs.F90 .
cp /home/hexu/cprojects/abinit/shared/common/src/28_numeric_noabirule/m_random_xoroshiro128plus.F90 .
